spring:
  application:
    name: CLRAIProducts

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.7
          max-tokens: 800

    mcp:
      server:
        name: product-server
        version: 0.0.1
        type: sync
        stdio: true
      client:
        enabled: true
        name: pharma-client
        version: 0.0.1
        toolcallback:
          enabled: true
        annotation-scanner:
          enabled: true
        type: sync
        stdio:
          connections:
            product-server:
              command: java
              args:
                - "-jar"
                - 'C:\Users\harald.bayer\Development\POS-full\CLRAIProducts\target\CLRAIProducts-0.0.1-SNAPSHOT.jar'



  main:
    web-application-type: none

server:
  port: 8080
  address: 0.0.0.0

logging:
  level:
    org.springframework.ai: DEBUG